project:
  type: website
  output-dir: docs

website:
  title: "Benjamini Mpinga"
  site-url: https://benjamini-mpinga.netlify.app/
  description: "Coding for all for better today and tommorow"
  
  navbar:
      right:
        - text: Blog
          href: blog.qmd 
        - icon: github
          href: https://github.com/tenesom/
        - icon: twitter
          href: https://twitter.com/benjamini20
        # - icon: youtube
        #   href: https://www.youtube.com/user/Alfrodo123
  #########################
  # You can ignore this part in the first step
        - icon: rss
          href: blog.xml
        - text: Ressources
          menu: 
            - text: R Weekly
              href: https://rweekly.org/
            - text: R Bloggers
              href: https://www.r-bloggers.com/
            - text: Semba-blog
              href: https://semba.netlify.app/
            - text: Michi-blog
              href: https://nyamisi.github.io/nyamisi/
        - text: Archive
          href: archive.qmd
  google-analytics: "14521548"
  cookie-consent: 
      type: express
      style: headline
      palette: dark
  twitter-card: 
    image: thumbnail_blog.png
    card-style: summary_large_image
    creator: "@rappa753"
  
# filters:
#   - code-filename
######################### 

format:
  html:
    theme: lux
  
 

